# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.31

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/homebrew/bin/cmake

# The command to remove a file.
RM = /opt/homebrew/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/andrejcyrkunov/CplusplusProjects/broker

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/andrejcyrkunov/CplusplusProjects/broker

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/opt/homebrew/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/opt/homebrew/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/andrejcyrkunov/CplusplusProjects/broker/CMakeFiles /Users/andrejcyrkunov/CplusplusProjects/broker//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/andrejcyrkunov/CplusplusProjects/broker/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named LiMQ

# Build rule for target.
LiMQ: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 LiMQ
.PHONY : LiMQ

# fast build rule for target.
LiMQ/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LiMQ.dir/build.make CMakeFiles/LiMQ.dir/build
.PHONY : LiMQ/fast

src/broker/core.o: src/broker/core.cpp.o
.PHONY : src/broker/core.o

# target to build an object file
src/broker/core.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LiMQ.dir/build.make CMakeFiles/LiMQ.dir/src/broker/core.cpp.o
.PHONY : src/broker/core.cpp.o

src/broker/core.i: src/broker/core.cpp.i
.PHONY : src/broker/core.i

# target to preprocess a source file
src/broker/core.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LiMQ.dir/build.make CMakeFiles/LiMQ.dir/src/broker/core.cpp.i
.PHONY : src/broker/core.cpp.i

src/broker/core.s: src/broker/core.cpp.s
.PHONY : src/broker/core.s

# target to generate assembly for a file
src/broker/core.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LiMQ.dir/build.make CMakeFiles/LiMQ.dir/src/broker/core.cpp.s
.PHONY : src/broker/core.cpp.s

src/consumer/core.o: src/consumer/core.cpp.o
.PHONY : src/consumer/core.o

# target to build an object file
src/consumer/core.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LiMQ.dir/build.make CMakeFiles/LiMQ.dir/src/consumer/core.cpp.o
.PHONY : src/consumer/core.cpp.o

src/consumer/core.i: src/consumer/core.cpp.i
.PHONY : src/consumer/core.i

# target to preprocess a source file
src/consumer/core.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LiMQ.dir/build.make CMakeFiles/LiMQ.dir/src/consumer/core.cpp.i
.PHONY : src/consumer/core.cpp.i

src/consumer/core.s: src/consumer/core.cpp.s
.PHONY : src/consumer/core.s

# target to generate assembly for a file
src/consumer/core.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LiMQ.dir/build.make CMakeFiles/LiMQ.dir/src/consumer/core.cpp.s
.PHONY : src/consumer/core.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LiMQ.dir/build.make CMakeFiles/LiMQ.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LiMQ.dir/build.make CMakeFiles/LiMQ.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LiMQ.dir/build.make CMakeFiles/LiMQ.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/producer/core.o: src/producer/core.cpp.o
.PHONY : src/producer/core.o

# target to build an object file
src/producer/core.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LiMQ.dir/build.make CMakeFiles/LiMQ.dir/src/producer/core.cpp.o
.PHONY : src/producer/core.cpp.o

src/producer/core.i: src/producer/core.cpp.i
.PHONY : src/producer/core.i

# target to preprocess a source file
src/producer/core.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LiMQ.dir/build.make CMakeFiles/LiMQ.dir/src/producer/core.cpp.i
.PHONY : src/producer/core.cpp.i

src/producer/core.s: src/producer/core.cpp.s
.PHONY : src/producer/core.s

# target to generate assembly for a file
src/producer/core.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LiMQ.dir/build.make CMakeFiles/LiMQ.dir/src/producer/core.cpp.s
.PHONY : src/producer/core.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... LiMQ"
	@echo "... src/broker/core.o"
	@echo "... src/broker/core.i"
	@echo "... src/broker/core.s"
	@echo "... src/consumer/core.o"
	@echo "... src/consumer/core.i"
	@echo "... src/consumer/core.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/producer/core.o"
	@echo "... src/producer/core.i"
	@echo "... src/producer/core.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

